### ISSUE TITLE
aurweb RPC interface

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#20]
This issue tracks aurweb changes.

**Comment by rmarquis** [comment]
You can add to your list that the RPC currently includes all architecture dependent (make)depends in the same arrays. See [here](https://lists.archlinux.org/pipermail/aur-dev/2014-December/003006.html) for details.

**Comment by AladW** [comment]
Added, thanks for the reminder.

**Comment by AladW** [comment]
Upstream issues for `repose`:
- [x] **repose** performance issues with large databases https://github.com/vodik/repose/issues/42
- [ ] **repose** does not take absolute paths to packages https://github.com/vodik/repose/issues/49
- [ ] **repose** failure on database signing https://github.com/vodik/repose/issues/46
- [ ] **repose** parsing errors
- [ ] **repose** segmentation faults

Removed from the first post as support will be removed from `aurbuild`, see #238.

**Comment by eli-schwartz** [comment]
https://bugs.archlinux.org/task/49946 fixed in git

Error codes for all in https://lists.archlinux.org/pipermail/pacman-dev/2017-September/022156.html
Currently in the patchqueue at https://git.archlinux.org/users/allan/pacman.git/commit/?h=patchqueue&id=ab2be5794de8a57426ec3fc0f631cc766a0b8227

**Comment by eli-schwartz** [comment]
> pacman vercmp alpha '' results in -1 (alpha < "") [FS#49093](https://bugs.archlinux.org/task/49093)

Submitted fix at https://lists.archlinux.org/pipermail/pacman-dev/2017-December/022211.html

**Comment by eli-schwartz** [comment]
>  **pacman** `vercmp alpha ''` results in `-1` (`alpha < ""`) [FS#49093](https://bugs.archlinux.org/task/49093)

What's the dead end here? `vercmp alpha ` is now a fatal error in the latest stable release. I don't think it's strictly necessary to call vercmp with quoted arguments, as any actual version in the wild, with a space in it, is invalid and can be checked as such -- vercmp doesn't do any checks at all to determine whether a pkgver is invalid or not.

From the bug report:
> Well, vercmp is useful in other cases, such as comparing sync/local versions (with pacman --print or expac) against the AUR RPC (with curl/json). If either string is empty, you'd have to be aware of the limitation, and workaround by e.g. setting -1 yourself if the variable is empty.

Anyway in this case I'd expect detecting a nonexistent package to be implemented via checking the returned contents of curl/expac, rather than making assumptions about the **version comparison**.

**Comment by AladW** [comment]
I guess it can be handled in a satisfactory way from the caller, unlike any of the other "dead end" issues. I moved it to "closed".

**Comment by micwoj92** [comment]
pacsift: no output if --sysroot is specified andrewgregory/pacutils#26

Should be marked as done I think, upstream issue was solved.
