### ISSUE TITLE
man1: updates for 2.x

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#217]
## Man pages
- [x]  `aur(1)`: explain how to add custom scripts (#305, #317) -> #540
  + [x] How to keep the size of `AURDEST` small (#317)
  + [x] Remove packages from a local repository (#305)
- [x] `aur-build(1)`: `/var/tmp` PKGDEST, default `makepkg` arguments
- [x] `aur-build(1)`: `GPGKEY` in `makepkg.conf` is ignored for `repo-add`
- [x] `aur-vercmp(1)`: explain `-u` (https://github.com/AladW/aurutils/commit/dd4c302997c5eaee752a54c974c237a2b952d5c8), `-c`
- [x] `aur-repo(1)`: add option descriptions
- [x] `aur-vercmp(1)`: add `--quiet`/`-q`
- [x] `aur-sync(1)`: add `--no-graph`
- [x] `aur-depends`: now takes input as arguments
- [x] `aur-fetch`: now takes input as arguments

## Procedures
- [x] Add information on _hosting_ a custom repository (https://github.com/AladW/aurutils/issues/247#issuecomment-304256312)
- [x] Pointers on general AUR usage ([wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository))

**Comment by Foxboron** [comment]
I made a overview of disparities inn documentation and missing options. Should be a complete list of all the documentations issues.


#### aurbuild:
- [ ] help string difference from manpage
- [ ] man synopsis missing options

#### aurchain:
- [ ] help string difference from man page
- [ ] missing zsh completion

#### aurcheck:
- [ ] missing zsh completion

#### aurfetch:
- [ ] missing man page
- [ ] missing zsh completion

#### aurgrep:
- [ ] missing man page
- [ ] missing help string
- [ ] missing zsh completion

#### aurqueue:
- [ ] missing help string

#### aursearch:
- [ ] help string difference from man page
- [ ] man synopsis missing options
- [ ] man page missing -n option

#### aursync:
- [ ] help string difference from man page
- [ ] missing flag documentation:
  - [ ] -B
    - [ ] Missing inn the zsh completion
    - [ ] The manpage and help says two different things.
  - [ ] -C
    - [ ] Missing inside the manpage synopsis
- [ ] makepkg and makechrootpkg missing from zsh completion

**Comment by AladW** [comment]
Awesome, thanks! I've copied the list to the first post.

**Comment by AladW** [comment]
Points are completed except for the aurfetch / aurgrep man pages and the makepkg completion. As makepkg and makechrootpkg have different options, the completion should be dynamic depending on if `-c` specified. I however don't know how to do that or the time to find out.

**Comment by AladW** [comment]
Another thing that should be documented is the workaround `aurbuild` takes to retrieve the exact package names with extension, i.e. `PKGDEST=/var/tmp`, and the resulting `find` filter to simulate `makepkg -f` behavior.

**Comment by AladW** [comment]
@Foxboron if you want to write a man page, `aur-src-ver` could use one! 😀

**Comment by AladW** [comment]
For the previous `zsh` completion files, see: //paste.xinu.at/m-hixxcT/

**Comment by AladW** [comment]
For completion, see #311.

**Comment by FichteFoll** [comment]
The page for `aur-vercmp` is out of date, too. I looked at it for a while, but I find it hard to make out what the options actually control. Also note that `-d` is slated for removal (#316).

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/dd4c302997c5eaee752a54c974c237a2b952d5c8 should explain what `-u` does

**Comment by AladW** [comment]
Another useful thing to have would be `ERRORS` sections to explain what to do on common errors (e.g. `aur-sync`, `aur-build`)

**Comment by jwhendy** [comment]
In trying to understand #509, I noticed that `aur sync` puts out this line:
```
Running makepkg --clean --sync --rmdeps
```
I wondered if `--sync ` had to do with why my manually built packages were failing to install after `repo-add`. The `--sync` option was of interest, is mentioned in `man aur build`, but I don't see it in `man makepkg`. Where might I find out that this does?

**Comment by AladW** [comment]
e8b38526f8bab314e2df2ec76d559350779fd165

**Comment by AladW** [comment]
Removed some points which I have no interest in adding (but for which PRs are accepted):

- [ ] `aur-build(1)`: mention multiple `-d` trick (#492)
- [ ] `aurhosting(7)` uses `repose`, while `aur-build(1)` uses `repo-add` (#312)
- [ ]  `aur(1)`: explain how to add custom scripts (#305, #317)
- [ ] `aur-depends(1)`: `depends`, `makedepends` and `checkdepends` are concatenated, which may give false dependency cycles in some cases. (#280)
- [ ] `aur-jobs(1)`: examples of parallel usage, cf. 69abd6f8d4a40313257851e64669e308c4c0ee2d
- [ ] `aur-sync(1)`, `aur-build(1)`: `ERRORS` section
- [ ] Add more example pipelines (#302, #316)
- [ ] How to keep the size of `AURDEST` small (#317)
- [ ] Expand on interplay between aur-repo-filter and aur-sync (#303)
- [ ] Workflow for locally modified AUR packages (#492)
- [ ] Workflow for VCS packages (#511)
