### ISSUE TITLE
prepare 2.0 release

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#451]
There's not much left here. I suggest the following:

- [x] Pull and test my local changes on the `devel` branch (#452)
- [x] Figure out what to do with `--provides` (#404)
- [x] Check options and formatting in man pages
- [x] Undo https://github.com/AladW/aurutils/commit/a69a992f38094694e03f70ff949f24dbb739d11d for now, it works better with #379 or #390.
- [x] Finish the man page for `aur-vercmp-devel`

Other issues like #217, #311, #379 or #444 could be addressed gradually. The real work will be to achieve the same degree of testing as `1.5`, since `aurutils-test` is gone. 

A `CHANGELOG` would also be nice, but not trivial with 800+ commits since the last release... :laughing:

**Comment by AladW** [comment]
We have bash completion and updated man pages, so I made a prerelease.

https://github.com/AladW/aurutils/releases/tag/2.0.0rc
