### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#497]
I've identified some issues where regression tests would be useful. This issue keeps track of those.

- [x] aur-build: build directory empty after makepkg => bash expansion fails · Issue #513
- [x] aursearch: fails silently on too many results (search type) · Issue #257
- [x] aurbuild: corrupted packages with --force · Issue #85
- [x] Aursync "cannot create directory /aursync" · Issue #216
- [x] aursearch: exit 0 when no results found (json_long/json_short) · Issue #187
- [x] Fix aurbuild fail on creating a new container by vorph1 · Pull Request #167
- [x] aurbuild: local repository is not available in the arch-nspawn container for pacman -Syu · Issue #461
- [x] AUR_REPO doesn't actually work · Issue #378
- [x] aur-sync: build order is inverted when installing poezio · Issue #414
- [x] aur-search hangs indefinitely. · Issue #403

**Comment by AladW** [comment]
All tests are pushed to the `tests` branch.
