### ISSUE TITLE
Prepare 3.0 release

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#577]
This is another big one so we should have some plan + prerelease cycle. I propose the following:

### General
- [x] Remove `aur-jobs` (#579)
  * The script is only used in `aur-sync`/`aur-srcver` and has no non-trivial functionality otherwise.
- [x] Rename `aur-rpc` to `aur-query` (#580)
  * "rpc" describes the protocol, while "query" describes the intent.
- [x] Replace `aur-vercmp-devel` with `aurvcs(7)` (#511)
  * See https://github.com/AladW/aurutils/issues/511#issuecomment-508938979
- [x] Replace `AUR_COLOR` with `NO_COLOR` (#599)

### Release
- [x] Update the changelog
  * @rafasc started work on this, see https://github.com/rafasc/aurutils/commit/6bb045d25bf04fb0612ddb5a487f61b5512d0975
- [x] `git shortlog --no-merges -s '2.3.1..3.0.0' | sort -r | awk '{ if ($1 > 2) { print $0; }; }'`

### Documentation/tests
- [x] `aur-build.1`
- [x] `aur-repo.1`
- [x] `aur-sync.1`
- [x] `aur-chroot.1`
- [x] `aur-fetch.1`
- [x] `aur-query.1` (description text still missing)
- [x] Regression tests (#497)

### `aur`
- [x] Add `AUR_EXEC_PATH` (#672)

### `aur-chroot`
- [x] Use static `pacman.conf` for chroot (#655)
  * Remove`-d`

### `aur-build`
- [x] Append options after `--` to the chroot makepkg (`-c`, #570)
- [x] Expose common makepkg options (compare `aur-sync`)
- [x] Only remove temporary files on clean exit (#593)
- [x] Remove the `SHELLOPTS` workaround, implement `AUR_DEBUG` in `aur` instead.
- [x] Remove default options to `makepkg` (#635)
- [x] Rename `-s` to `-S` (`--sign`)
- [x] Split makepkg command to `makepkg -od` and `makepkg --noextract` if `--pkgver` is specified (#708)

### `aur-fetch`
- [x] Add `--sync` (`=auto`, `=rebase`, `=reset`) to preserve or reset local commits (#639)
- [x] Add `--results` to indicate if a given `git` repo was cloned, rebased or fetched (#379, #639)
- [x] `orderfile` is now set in `aur-sync` (`$XDG_CONFIG_HOME/aurutils/sync`)
- [x] Remove `--logdir`, `--verbose`

### `aur-pkglist`
- [x] Replace `wget` with `curl` (#703) 

### `aur-query`
- [x] Replace `wget` with `curl` (#703)

### `aur-repo`
- [x] Add `--table` (#607)
- [x] Add `--path` (#649)
- [x] Print canonical path of repository (#702)

### `aur-srcver`
- [x] Remove `parallel` (#583)

### `aur-sync`
- [x] Add `AUR_CONFIRM_PAGER` (#689)
- [x] Add `--format`
- [x] Add `--provides-from`
- [x] Enable `--provides` by default (disable with `--noprovides`)
- [x] Save inspected revisions to `$XDG_DATA_HOME/aurutils/view`
- [x] Remove `parallel` (#582)
- [x] Remove `less` (#689)
- [x] Rename `--nover-shallow` to `--nover-argv`
- [x] Rename `-s` to `-S` (`--sign`)

**Comment by Earnestly** [comment]
As an aside, this should probably be a `3.0` release instead of a minor.

**Comment by FichteFoll** [comment]
It should be noted that `AUR_SEEN` replaced `AURUTILS_SEEN` (via https://github.com/AladW/aurutils/pull/620), unless a fallback has been added that I missed.

**Comment by AladW** [comment]
Sure, but AURUTILS_SEEN was not present in 2.3 (and master has no guarantees for the end-user)

**Comment by FichteFoll** [comment]
Are you sure about that? I'm on `2.3.1.r52.g6da4f82-1` and I've been using it for a while.

**Comment by AladW** [comment]
Yes, because that's the master branch (51 commits past 2.3.1). See the
pkgver() function in the PKGBUILD.

**Comment by AladW** [comment]
Functionality-wise I would say 3.0.0 is done, we just need to update the documentation/changelog (and fix #727).

**Comment by AladW** [comment]
All with the last batch of PRs (#742, #743, #744, #745). The only thing that remains is writing the changelog...

**Comment by AladW** [comment]
Released `3.0.0rc2`.

**Comment by AladW** [comment]
Released `3.0.0rc3`. This should be the last RC.

**Comment by AladW** [comment]
Released `3.0.0` 🥳
